{% set name = "lpython_emulation" %}
{% set version = "0.0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lpython_emulation-{{ version }}.tar.gz
  sha256: 72d4623c0bd88c833443162bfbf7d42c2ed1db07f1c2306f481c9910f85ed229

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - lpython
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Shaikh-Ubaid/lpython_packages
  summary: Package for adding type information to python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Shaikh-Ubaid
